spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 37267676823-ds6c5bsao7742hok3usqn30t2uqlec75.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: test@gmail.com
  secret_key: study-springboot


